version: "3"

services:

    db:
        image: postgres:9.5
        environment:
            - POSTGRES_USER=$APP_DB_USERNAME
            - POSTGRES_PASSWORD=$APP_DB_PASSWORD
            - POSTGRES_DB=$APP_DB_NAME
        ports:
            - $APP_DB_PORT:$APP_DB_PORT
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    app:
        build: .
        command:
            sh -c "./wait-for db:$APP_DB_PORT -- ./entrypoint.sh"
        restart: on-failure
        environment:
            - APP_DB_USERNAME=$APP_DB_USERNAME
            - APP_DB_PASSWORD=$APP_DB_PASSWORD
            - APP_DB_NAME=$APP_DB_NAME
            - APP_DB_HOSTNAME=db
            - APP_DB_PORT=$APP_DB_PORT
            - APP_PORT=$APP_PORT
            - MIGRATE=$MIGRATE
            - DEBUG=$DEBUG
        ports:
            - $APP_PORT:$APP_PORT
        depends_on:
            - db

volumes:
    db-data:
        driver: local
