"""initial

Revision ID: 3d49249318c5
Revises: 
Create Date: 2020-02-14 16:40:07.111565

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
from sqlalchemy.sql.expression import text


# revision identifiers, used by Alembic.
revision = '3d49249318c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nodepath', 'nodelist', [text('md5(ltree2text(path))')])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodelist')
    # ### end Alembic commands ###
